# Generated by Django 6.0.5 on 2026-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('finance', 'Finance'), ('community', 'Community')], default='community', max_length=30),
        ),
    ]
