# Generated by Django 6.0.5 on 2026-05-12 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('aggregated', 'Aggregated')], default='internal', max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='external_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'journalist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
