# Generated by Django 6.0.5 on 2026-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_article_article_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('finance', 'Finance'), ('current_affairs', 'Current Affairs'), ('community', 'Community')], default='community', max_length=30),
        ),
    ]
