# Generated by Django 6.0.5 on 2026-05-12 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='editor_publishers', to=settings.AUTH_USER_MODEL)),
                ('journalists', models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
